// <auto-generated />
using System;
using LoanApplicationApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanApplicationApp.API.Migrations
{
    [DbContext(typeof(LoanApplicationDbContext))]
    partial class LoanApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanApplicationApp.API.Models.Domain.Application", b =>
                {
                    b.Property<long>("ApplicationNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApplicationNo"));

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankStatementFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditScore")
                        .HasColumnType("int");

                    b.Property<string>("IdCopyFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LoanProcessorNo")
                        .HasColumnType("bigint");

                    b.Property<double>("MonthlySalary")
                        .HasColumnType("float");

                    b.Property<string>("PaySlipFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationNo");

                    b.HasIndex("LoanProcessorNo");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("LoanApplicationApp.API.Models.Domain.LoanProcessor", b =>
                {
                    b.Property<long>("LoanProcessorNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LoanProcessorNo"));

                    b.Property<Guid>("ProcessorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoanProcessorNo");

                    b.ToTable("LoanProcessors");
                });

            modelBuilder.Entity("LoanApplicationApp.API.Models.Domain.Application", b =>
                {
                    b.HasOne("LoanApplicationApp.API.Models.Domain.LoanProcessor", "LoanProcessor")
                        .WithMany("Applications")
                        .HasForeignKey("LoanProcessorNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanProcessor");
                });

            modelBuilder.Entity("LoanApplicationApp.API.Models.Domain.LoanProcessor", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
